In [13]:
# Importing numpy library
import numpy as np

In [14]:
# Creating array A
A = np.array( [[ 71, 82],
                 [ 48, 23]] )

In [15]:
# Creating array B
B = np.array([[5, 2],
            [3, 7]])

In [16]:
# Adding arrays and printing it out
print("Array sum:\n", A + B)

Array sum:
 [[76 84]
 [51 30]]


In [17]:
# Multiply arrays A and B (elementwise multiplication)
print("Array multiplication:\n", A*B)

Array multiplication:
 [[355 164]
 [144 161]]


In [18]:
# Multiply arrays A and B (matrix multiplication)
print("Matrix multiplication:\n", A.dot(B))

Matrix multiplication:
 [[601 716]
 [309 257]]
