In [13]:
# Import Numpy library  
import numpy as np

In [14]:
# Initialize list values
y_pred = [0, 2, 0, 2, 1,3]
y_true = [0, 2, 3, 2, 1,3]

In [15]:
# Importing confusion_matrix metric from sklearn
from sklearn.metrics import confusion_matrix

In [16]:
# Printing out the confusion matrix
matrix = confusion_matrix(y_true, y_pred)    
print(matrix)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [1 0 0 1]]
